export const CURSO_LIST_REQUEST = "CURSO_LIST_REQUEST";
export const CURSO_LIST_SUCCESS = "CURSO_LIST_SUCCESS";
export const CURSO_LIST_FAIL = "CURSO_LIST_FAIL";

export const BLOCO_LIST_REQUEST = "BLOCO_LIST_REQUEST";
export const BLOCO_LIST_SUCCESS = "BLOCO_LIST_SUCCESS";
export const BLOCO_LIST_FAIL = "BLOCO_LIST_FAIL";

export const ANO_LIST_REQUEST = "ANO_LIST_REQUEST";
export const ANO_LIST_SUCCESS = "ANO_LIST_SUCCESS";
export const ANO_LIST_FAIL = "ANO_LIST_FAIL";

export const CURSO_DETAILS_REQUEST = "CURSO_DETAILS_REQUEST";
export const CURSO_DETAILS_SUCCESS = "CURSO_DETAILS_SUCCESS";
export const CURSO_DETAILS_FAIL = "CURSO_DETAILS_FAIL";

export const BLOCO_DETAILS_REQUEST = "BLOCO_DETAILS_REQUEST";
export const BLOCO_DETAILS_SUCCESS = "BLOCO_DETAILS_SUCCESS";
export const BLOCO_DETAILS_FAIL = "BLOCO_DETAILS_FAIL";

export const ANO_DETAILS_REQUEST = "ANO_DETAILS_REQUEST";
export const ANO_DETAILS_SUCCESS = "ANO_DETAILS_SUCCESS";
export const ANO_DETAILS_FAIL = "ANO_DETAILS_FAIL";



export const GRADE_DELETE_REQUEST = "GRADE_DELETE_REQUEST";

export const GRADE_DELETE_SUCCESS = "GRADE_DELETE_SUCCESS";

export const GRADE_DELETE_FAIL = "GRADE_DELETE_FAIL";

export const GRADE_CREATE_REQUEST = "GRADE_CREATE_REQUEST";

export const GRADE_CREATE_SUCCESS = "GRADE_CREATE_SUCCESS";

export const GRADE_CREATE_FAIL = "GRADE_CREATE_FAIL";

export const GRADE_CREATE_RESET = "GRADE_CREATE_RESET";


export const GRADE_UPDATE_REQUEST = "GRADE_UPDATE_REQUEST";

export const GRADE_UPDATE_SUCCESS = "GRADE_UPDATE_SUCCESS";

export const GRADE_UPDATE_FAIL = "GRADE_UPDATE_FAIL";

export const GRADE_UPDATE_RESET = "GRADE_UPDATE_RESET";

export const GRADE_CREATE_DIAS_REQUEST = "GRADE_CREATE_DIAS_REQUEST";

export const GRADE_CREATE_DIAS_SUCCESS = "GRADE_CREATE_DIAS_SUCCESS";

export const GRADE_CREATE_DIAS_FAIL = "GRADE_CREATE_DIAS_FAIL";

export const GRADE_CREATE_DIAS_RESET = "GRADE_CREATE_DIAS_RESET";
///////////////////////////////////////////////////////////////////

export const GRADE_URL_GET = "GRADE_URL_GET";


export const GRADE_URL_REMOVE = "GRADE_URL_REMOVE";
