export const GRADE_LIST_REQUEST = "GRADE_LIST_REQUEST";

export const GRADE_LIST_SUCCESS = "GRADE_LIST_SUCCESS";

export const GRADE_LIST_FAIL = "GRADE_LIST_FAIL";

export const GRADE_DETAILS_REQUEST = "GRADE_DETAILS_REQUEST";

export const GRADE_DETAILS_SUCCESS = "GRADE_DETAILS_SUCCESS";

export const GRADE_DETAILS_FAIL = "GRADE_DETAILS_FAIL";

export const GRADE_DELETE_REQUEST = "GRADE_DELETE_REQUEST";

export const GRADE_DELETE_SUCCESS = "GRADE_DELETE_SUCCESS";

export const GRADE_DELETE_FAIL = "GRADE_DELETE_FAIL";

export const GRADE_CREATE_REQUEST = "GRADE_CREATE_REQUEST";

export const GRADE_CREATE_SUCCESS = "GRADE_CREATE_SUCCESS";

export const GRADE_CREATE_FAIL = "GRADE_CREATE_FAIL";

export const GRADE_CREATE_RESET = "GRADE_CREATE_RESET";


export const GRADE_UPDATE_REQUEST = "GRADE_UPDATE_REQUEST";

export const GRADE_UPDATE_SUCCESS = "GRADE_UPDATE_SUCCESS";

export const GRADE_UPDATE_FAIL = "GRADE_UPDATE_FAIL";

export const GRADE_UPDATE_RESET = "GRADE_UPDATE_RESET";

export const GRADE_CREATE_DIAS_REQUEST = "GRADE_CREATE_DIAS_REQUEST";

export const GRADE_CREATE_DIAS_SUCCESS = "GRADE_CREATE_DIAS_SUCCESS";

export const GRADE_CREATE_DIAS_FAIL = "GRADE_CREATE_DIAS_FAIL";

export const GRADE_CREATE_DIAS_RESET = "GRADE_CREATE_DIAS_RESET";
///////////////////////////////////////////////////////////////////

export const GRADE_URL_GET = "GRADE_URL_GET";


export const GRADE_URL_REMOVE = "GRADE_URL_REMOVE";
